import type { createNodeActionsController } from "./nodeActionsController";
import type { createNodeHubController } from "./nodeHubController";
import type { createNodeLifecycleController } from "./nodeLifecycleController";
import type { createNodeLoggingController } from "./nodeLoggingController";
import type { createNodePeerController } from "./nodePeerController";
import type { createNodePeerSelectors } from "./nodePeerSelectors";
import type { createNodeProjectionController } from "./nodeProjectionController";
import type { NodeStoreState } from "./nodeStoreState";
import type { createNodeTransportController } from "./nodeTransportController";

export function createNodeStoreApi(
  state: NodeStoreState,
  logging: ReturnType<typeof createNodeLoggingController>,
  peers: ReturnType<typeof createNodePeerController>,
  projections: ReturnType<typeof createNodeProjectionController>,
  hub: ReturnType<typeof createNodeHubController>,
  selectors: ReturnType<typeof createNodePeerSelectors>,
  lifecycle: ReturnType<typeof createNodeLifecycleController>,
  actions: ReturnType<typeof createNodeActionsController>,
  transport: ReturnType<typeof createNodeTransportController>,
) {
  return {
    settings: state.settings,
    nodeConfigRestartRequired: state.nodeConfigRestartRequired,
    watchStatusServer: state.watchStatusServer,
    status: state.status,
    syncStatus: state.syncStatus,
    operationalSummary: state.operationalSummary,
    announceByDestination: state.announceByDestination,
    hubDirectorySnapshot: state.hubDirectorySnapshot,
    hubDirectoryPeers: selectors.hubDirectoryPeers,
    hubAnnounceCandidates: selectors.hubAnnounceCandidates,
    effectiveConnectedMode: selectors.effectiveConnectedMode,
    hubRegistration: state.hubRegistration,
    hubBootstrapProfile: selectors.hubBootstrapProfile,
    hubRegistrationReady: selectors.hubRegistrationReady,
    hubRegistrationPending: selectors.hubRegistrationPending,
    hubRegistrationSummary: selectors.hubRegistrationSummary,
    logs: state.logs,
    nodeControlEntries: state.nodeControlEntries,
    lastError: state.lastError,
    readinessError: selectors.readinessErrorMessage,
    lastHubRefreshAt: state.lastHubRefreshAt,
    discoveredByDestination: state.discoveredByDestination,
    savedByDestination: state.savedByDestination,
    allPeers: selectors.allPeers,
    discoveredPeers: selectors.discoveredPeers,
    remAnnouncedPeers: selectors.remAnnouncedPeers,
    savedPeers: selectors.savedPeers,
    savedVisiblePeers: selectors.savedVisiblePeers,
    connectedPeers: selectors.connectedPeers,
    reachablePeers: selectors.reachablePeers,
    propagationEligibleEventPeerRoutes: selectors.propagationEligibleEventPeerRoutes,
    connectedDestinations: selectors.connectedDestinations,
    intentionalPeerDestinations: selectors.intentionalPeerDestinations,
    connectedLinkDestinations: selectors.connectedLinkDestinations,
    connectedEventPeerRoutes: selectors.connectedEventPeerRoutes,
    visiblePeerCount: selectors.visiblePeerCount,
    savedPeerCount: selectors.savedPeerCount,
    connectedPeerCount: selectors.connectedPeerCount,
    reachablePeerCount: selectors.reachablePeerCount,
    startupSettling: state.startupSettling,
    bestPropagationNodeHex: selectors.bestPropagationNodeHex,
    telemetryDestinations: state.telemetryDestinations,
    plugins: state.plugins,
    pluginSensors: state.pluginSensors,
    savedDestinations: selectors.savedDestinations,
    initialized: state.initialized,
    ready: selectors.ready,
    peerDisplayState: selectors.peerDisplayState,
    peerPresenceTimestamp: selectors.peerPresenceTimestamp,
    peerCachedPresenceTimestamp: selectors.peerCachedPresenceTimestamp,
    peerPresenceState: selectors.peerPresenceState,
    init: lifecycle.init,
    startNode: lifecycle.startNode,
    stopNode: lifecycle.stopNode,
    restartNode: lifecycle.restartNode,
    connectPeer: lifecycle.connectPeer,
    disconnectPeer: lifecycle.disconnectPeer,
    connectAllSaved: lifecycle.connectAllSaved,
    disconnectAllSaved: lifecycle.disconnectAllSaved,
    refreshHubDirectory: actions.refreshHubDirectory,
    refreshPluginProjection: projections.refreshPluginProjection,
    refreshPluginSensors: projections.refreshPluginSensors,
    approvePluginPublisher: projections.approvePluginPublisher,
    revokePluginPublisher: projections.revokePluginPublisher,
    setPluginEnabled: projections.setPluginEnabled,
    grantPluginCapabilities: projections.grantPluginCapabilities,
    openPluginConfiguration: projections.openPluginConfiguration,
    refreshHubRegistrationState: hub.refreshHubRegistrationState,
    bootstrapHubRegistration: hub.bootstrapHubRegistration,
    forgetHubRegistryLinkage: actions.forgetHubRegistryLinkage,
    setAnnounceCapabilities: actions.setAnnounceCapabilities,
    savePeer: actions.savePeer,
    removePeer: actions.removePeer,
    unsavePeer: actions.unsavePeer,
    setPeerLabel: actions.setPeerLabel,
    updateSettings: actions.updateSettings,
    refreshWatchStatusServerSettings: projections.refreshWatchStatusServerSettings,
    updateWatchStatusServerSettings: projections.updateWatchStatusServerSettings,
    getSavedPeerList: actions.getSavedPeerList,
    importPeerList: actions.importPeerList,
    parsePeerListText: actions.parsePeerListText,
    logUi: logging.logUi,
    announceNow: transport.announceNow,
    requestPeerIdentity: transport.requestPeerIdentity,
    sendBytes: transport.sendBytes,
    sendBytesDirect: transport.sendBytesDirect,
    sendBytesViaPropagation: transport.sendBytesViaPropagation,
    sendLxmf: transport.sendLxmf,
    onClientEvent: transport.onClientEvent,
    getSosSettings: transport.getSosSettings,
    setSosSettings: transport.setSosSettings,
    setSosPin: transport.setSosPin,
    getSosStatus: transport.getSosStatus,
    triggerSos: transport.triggerSos,
    deactivateSos: transport.deactivateSos,
    submitSosTelemetry: transport.submitSosTelemetry,
    listSosAlerts: transport.listSosAlerts,
    listSosLocations: transport.listSosLocations,
    listSosAudio: transport.listSosAudio,
    recordSosAudio: transport.recordSosAudio,
    setActivePropagationNode: transport.setActivePropagationNode,
    requestLxmfSync: transport.requestLxmfSync,
    broadcastBytes: transport.broadcastBytes,
    broadcastJson: transport.broadcastJson,
    sendJson: transport.sendJson,
    resolvePeerLxmfDestinationByIdentity: peers.resolvePeerLxmfDestinationByIdentity,
    destinationHasCapability: transport.destinationHasCapability,
    reinitializeClient: transport.reinitializeClient,
    setLastError: logging.setLastError,
    assertReadyForOutbound: transport.assertReadyForOutbound,
    assertHubRoutingReadyForOutbound: transport.assertHubRoutingReadyForOutbound,
  };
}
